### ISSUE TITLE
Toying around with this

### ISSUE THREAD

**Issue by STRUDSO** [GoogleCloudPlatform/recommender-iac-pipeline-nodejs-tutorial#3]
https://github.com/GoogleCloudPlatform/recommender-iac-pipeline-nodejs-tutorial/blob/1c24dc04654f489797fe234a165659fda50b9e25/parser-service/recommender.js#L133

you have location as global, does that even work with:
google.compute.instance.MachineTypeRecommender

https://cloud.google.com/recommender/docs/vm-instance-rightsizing-recommender#location

I think you need to specify the exact zone for this to work

**Comment by pyljain** [comment]
Thank you for raising the issue. It used to work with global when the product was in preview / beta. I'll update the code to use zones as locations for MachineTypeRecommender. I'll leave this issue open till then.

**Comment by idofl** [comment]
The code was updated and a location can now be passed from Cloud Scheduler to parser service.

https://github.com/GoogleCloudPlatform/recommender-iac-pipeline-nodejs-tutorial/pull/8
